services:
  - type: web
    name: n8n
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: yourusername
      - key: N8N_BASIC_AUTH_PASSWORD
        value: yourpassword
      - key: WEBHOOK_URL
        value: https://n8n-onrender.onrender.com/
